# 02 – Ön İşleme ve Öznitelik Mühendisliği
İndikatör hesaplama ve feature pipeline hazırlığı

In [1]:
from src.load_data import load_filtered, filter_coin, get_all_tickers
from src.indicators import add_all_indicators
from src.engineering import prepare_features, prepare_all_coins
import pandas as pd

In [2]:
df = load_filtered()
print(df.shape)
df.head()

229359 satır, 100 ticker yüklendi
Kalite kontrolü geçti: 100 coin, 229359 satır
(229359, 6)

  ticker       date     open     high      low    close
0    BTC 2010-07-17  0.04951  0.04951  0.04951  0.04951
1    BTC 2010-07-18  0.04951  0.08585  0.04951  0.08584
2    BTC 2010-07-19  0.08584  0.09307  0.07723  0.08080
3    BTC 2010-07-20  0.08080  0.08181  0.07426  0.07474
4    BTC 2010-07-21  0.07474  0.07921  0.06634  0.07921

In [3]:
tickers = get_all_tickers(df)
print(f"Toplam coin: {len(tickers)}")
print(tickers)

Toplam coin: 100
['1INCH', 'AAVE', 'ADA', 'ALGO', 'AMP', 'AR', 'ATOM', 'AVAX', 'AXS', 'BAT', 'BCH', 'BNB', 'BSV', 'BTC', 'BTT', 'CAKE', 'CFX', 'CHZ', 'COMP', 'CRO', 'CRV', 'CVX', 'DAI', 'DASH', 'DCR', 'DOGE', 'DOT', 'EGLD', 'ENS', 'ETC', 'ETH', 'FET', 'FIL', 'FTT', 'GALA', 'GLM', 'GNO', 'GRT', 'GT', 'HBAR', 'HNT', 'ICP', 'IMX', 'INJ', 'IOTA', 'JST', 'KCS', 'LDO', 'LEO', 'LINK', 'LPT', 'LTC', 'MANA', 'MX', 'NEAR', 'NEO', 'NEXO', 'NFT', 'OKB', 'PAXG', 'POL', 'QNT', 'QTUM', 'RAY', 'RSR', 'RUNE', 'RVN', 'SAND', 'SHIB', 'SNX', 'SOL', 'STX', 'SUN', 'SYRUP', 'TEL', 'TFUEL', 'THETA', 'TRAC', 'TRX', 'TUSD', 'TWT', 'UNI', 'USDC', 'USDD', 'USDT', 'VET', 'WEMIX', 'XAUt', 'XCN', 'XDC', 'XEC', 'XLM', 'XMR', 'XRP', 'XTZ', 'XVG', 'YFI', 'ZEC', 'ZEN', 'ZRX']

In [4]:
btc = filter_coin(df, "BTC")
print(btc.shape)
btc.head()

(5665, 4)

               open     high      low    close
date
2010-07-17  0.04951  0.04951  0.04951  0.04951
2010-07-18  0.04951  0.08585  0.04951  0.08584
2010-07-19  0.08584  0.09307  0.07723  0.08080
2010-07-20  0.08080  0.08181  0.07426  0.07474
2010-07-21  0.07474  0.07921  0.06634  0.07921

In [5]:
btc_ind = add_all_indicators(btc)
print("Eklenen sütunlar:", btc_ind.columns.tolist())
btc_ind.tail(3)

Eklenen sütunlar: ['open', 'high', 'low', 'close', 'rsi_14', 'macd', 'macd_hist', 'macd_signal', 'bb_lower', 'bb_mid', 'bb_upper', 'ema_7', 'ema_14', 'ema_21', 'ema_50', 'atr_14']

,open,high,low,close,rsi_14,macd,macd_hist,macd_signal,bb_lower,bb_mid,bb_upper,ema_7,ema_14,ema_21,ema_50,atr_14
date,,,,,,,,,,,,,,,,
2026-03-06,71230.98,71392.86,67753.29,68325.29,46.717389,-1204.485639,1005.013502,-2209.499141,63697.650504,67765.3075,71832.964496,69135.343054,68672.145786,69182.436374,74143.456045,3617.477224
2026-03-07,68308.87,68542.19,66949.88,67278.84,44.934716,-1227.900177,785.279171,-2013.179348,63647.577505,67683.2680,71718.958495,68671.217291,68486.371681,69009.382158,73874.255416,3472.822423
2026-03-08,67278.83,68213.47,65651.30,66269.92,43.222244,-1312.735383,560.355172,-1873.090555,63507.955564,67568.2420,71628.528436,68070.892968,68190.844790,68760.340144,73576.046184,3407.775821

In [6]:
btc_ready = prepare_features(btc)
print("Final shape:", btc_ready.shape)
print("Sütunlar:", btc_ready.columns.tolist())
btc_ready.tail(3)

Final shape: (5615, 31)
Sütunlar: ['open', 'high', 'low', 'close', 'rsi_14', 'macd', 'macd_hist', 'macd_signal', 'bb_lower', 'bb_mid', 'bb_upper', 'ema_7', 'ema_14', 'ema_21', 'ema_50', 'atr_14', 'close_lag_1', 'close_lag_2', 'close_lag_3', 'close_lag_5', 'close_lag_7', 'rolling_mean_5', 'rolling_std_5', 'rolling_mean_10', 'rolling_std_10', 'daily_range', 'body_size', 'upper_shadow', 'lower_shadow', 'daily_return', 'direction']

,open,high,low,close,rsi_14,macd,macd_hist,macd_signal,bb_lower,bb_mid,...,rolling_mean_5,rolling_std_5,rolling_mean_10,rolling_std_10,daily_range,body_size,upper_shadow,lower_shadow,daily_return,direction
date,,,,,,,,,,,,,,,,,,,,,
2026-03-05,72727.66,73565.50,70648.00,71222.78,52.023931,-1263.628019,1197.124498,-2460.752516,63669.417466,67845.6310,...,69417.482,2840.627751,68017.310,2657.998422,2917.50,1504.88,837.84,574.78,-2.069199,0.0
2026-03-06,71230.98,71392.86,67753.29,68325.29,46.717389,-1204.485639,1005.013502,-2209.499141,63697.650504,67765.3075,...,70021.140,1920.382140,68433.896,2286.695217,3639.57,2905.69,161.88,572.00,-4.068207,0.0
2026-03-07,68308.87,68542.19,66949.88,67278.84,44.934716,-1227.900177,785.279171,-2013.179348,63647.577505,67683.2680,...,69579.088,2291.918581,68313.246,2315.328601,1592.31,1030.03,233.32,328.96,-1.531571,0.0

In [7]:
df_all = prepare_all_coins(df)
print("Tüm coinler shape:", df_all.shape)
print("Ticker sayısı:", df_all["ticker"].nunique())
df_all.head()

Tüm coinler shape: (224359, 32)
Ticker sayısı: 100

,open,high,low,close,rsi_14,macd,macd_hist,macd_signal,bb_lower,bb_mid,...,rolling_std_5,rolling_mean_10,rolling_std_10,daily_range,body_size,upper_shadow,lower_shadow,daily_return,direction,ticker
date,,,,,,,,,,,,,,,,,,,,,
2021-02-26,3.906,5.182,3.770,4.509,51.743332,0.135691,-0.247455,0.383146,3.691585,4.82840,...,0.442994,4.4736,0.548779,1.412,0.603,0.673,0.136,15.437788,0.0,1INCH
2021-02-27,4.509,4.877,4.000,4.157,47.995661,0.101520,-0.225301,0.326821,3.614622,4.78755,...,0.359927,4.4043,0.539646,0.877,0.352,0.368,0.157,-7.806609,0.0,1INCH
2021-02-28,4.157,4.161,3.519,3.817,44.632993,0.046468,-0.224282,0.270750,3.493045,4.71105,...,0.337720,4.3085,0.551432,0.642,0.340,0.004,0.298,-8.178975,1.0,1INCH
2021-03-01,3.817,4.230,3.792,4.103,47.937301,0.025621,-0.196103,0.221725,3.427745,4.66350,...,0.268445,4.2597,0.545211,0.438,0.286,0.127,0.025,7.492795,0.0,1INCH
2021-03-02,4.103,4.374,3.810,4.022,47.080317,0.002535,-0.175351,0.177887,3.357463,4.62190,...,0.252180,4.1455,0.445175,0.564,0.081,0.271,0.212,-1.974165,1.0,1INCH

In [8]:
df_all.describe()

,open,high,low,close,rsi_14,macd,macd_hist,macd_signal,bb_lower,bb_mid,...,rolling_mean_5,rolling_std_5,rolling_mean_10,rolling_std_10,daily_range,body_size,upper_shadow,lower_shadow,daily_return,direction
count,2.243590e+05,2.243590e+05,2.243590e+05,2.243590e+05,224359.000000,224359.000000,224359.000000,224359.000000,224359.000000,2.243590e+05,...,2.243590e+05,224359.000000,2.243590e+05,224359.000000,224359.000000,224359.000000,224359.000000,224359.000000,224359.000000,224359.000000
mean,6.984050e+02,7.165288e+02,6.790266e+02,6.986249e+02,49.266001,2.069182,-0.126301,2.195483,614.545887,6.962791e+02,...,6.981068e+02,20.712855,6.975041e+02,28.899016,37.502162,17.817171,9.105250,10.579741,0.869419,0.484723
std,5.842215e+03,5.969706e+03,5.704627e+03,5.843117e+03,12.288304,211.378967,62.808068,200.359898,5273.068356,5.818402e+03,...,5.837224e+03,196.809828,5.830768e+03,261.247590,362.660562,206.896166,100.673107,122.352255,120.155008,0.499768
min,3.019600e-07,3.036880e-07,2.992550e-07,3.025600e-07,1.507474,-5957.295825,-4207.102666,-5223.476171,-27.549125,3.104288e-07,...,3.055230e-07,0.000000,3.078992e-07,0.000000,0.000000,0.000000,0.000000,0.000000,-98.604870,0.000000
25%,2.224190e-01,2.315450e-01,2.129630e-01,2.223655e-01,40.783937,-0.077839,-0.010206,-0.074895,0.174195,2.232640e-01,...,2.224754e-01,0.003773,2.228337e-01,0.005517,0.007991,0.002020,0.001092,0.001070,-2.357386,0.000000
50%,1.777000e+00,1.865570e+00,1.691130e+00,1.777000e+00,48.096708,-0.000228,0.000020,-0.000209,1.368110,1.790539e+00,...,1.782472e+00,0.060524,1.784737e+00,0.090714,0.116190,0.037000,0.020000,0.020000,-0.003313,0.000000
75%,1.971089e+01,2.057440e+01,1.884970e+01,1.971285e+01,56.558954,0.031302,0.020969,0.030287,15.821559,1.972050e+01,...,1.972172e+01,0.751265,1.970346e+01,1.093620,1.437700,0.508310,0.292800,0.290000,2.218249,1.000000
max,1.251727e+05,1.263006e+05,1.228125e+05,1.251730e+05,99.855097,7015.041692,2351.929757,6427.568489,116370.366610,1.182768e+05,...,1.231305e+05,13351.126200,1.212152e+05,15445.489960,38639.800000,26893.700000,12379.800000,10430.000000,53040.096618,1.000000